#Linkin Park song One more Light lryics

puts "Linkin Park One More Light"
puts "Should've stayed, were there signs, I ignored?"
puts "Can I help you, not to hurt, anymore?"
puts "We saw brilliance, when the world, was asleep"
puts "There are things that we can have, but can't keep"
puts "If they say"
puts "Who cares if one more light goes out?"
puts "In a sky of a million stars"
puts "It flickers, flickers"
puts "Who cares when someone's time runs out?"
puts "If a moment is all we are"
puts "We're quicker, quicker"
puts "Who cares if one more light goes out?"
puts "Well I do"
puts "The reminders pull the floor from your feet"
puts "In the kitchen, one more chair than you need oh"
puts "And you're angry, and you should be, it's not fair"
puts "Just 'cause you can't see it, doesn't mean it, isn't there"
puts "If they say"
puts "Who cares if one more light goes out?"
puts "In a sky of a million stars"
puts "It flickers, flickers"
puts "Who cares when someone's time runs out?"
puts "If a moment is all we are"
puts "We're quicker, quicker"
puts "Who cares if one more light goes out?"
puts "Well I do"
puts "Who cares if one more light goes out?"
puts "In a sky of a million stars"
puts "It flickers, flickers"
puts "Who cares when someone's time runs out?"
puts "If a moment is all we are"
puts "We're quicker, quicker"
puts "Who cares if one more light goes out?"
puts "Well I do"
puts "Well I do"
